// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignScore(arg1, arg2, arg3) {
  return window['go']['main']['App']['AssignScore'](arg1, arg2, arg3);
}

export function BackupDatabase() {
  return window['go']['main']['App']['BackupDatabase']();
}

export function CheckDB() {
  return window['go']['main']['App']['CheckDB']();
}

export function GenerateGroupEvaluationPDF() {
  return window['go']['main']['App']['GenerateGroupEvaluationPDF']();
}

export function GenerateOrtsverbandEvaluationPDF() {
  return window['go']['main']['App']['GenerateOrtsverbandEvaluationPDF']();
}

export function GeneratePDF() {
  return window['go']['main']['App']['GeneratePDF']();
}

export function GenerateParticipantCertificates() {
  return window['go']['main']['App']['GenerateParticipantCertificates']();
}

export function GetAllGroups() {
  return window['go']['main']['App']['GetAllGroups']();
}

export function GetGroupEvaluations() {
  return window['go']['main']['App']['GetGroupEvaluations']();
}

export function GetOrtsverbandEvaluations() {
  return window['go']['main']['App']['GetOrtsverbandEvaluations']();
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function ShowGroups() {
  return window['go']['main']['App']['ShowGroups']();
}

export function ShowStations() {
  return window['go']['main']['App']['ShowStations']();
}
