// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignScore(arg1, arg2, arg3) {
  return window['go']['main']['App']['AssignScore'](arg1, arg2, arg3);
}

export function BackupDatabase() {
  return window['go']['main']['App']['BackupDatabase']();
}

export function CheckDB() {
  return window['go']['main']['App']['CheckDB']();
}

export function CheckStartup() {
  return window['go']['main']['App']['CheckStartup']();
}

export function ConvertMasterExcel(arg1) {
  return window['go']['main']['App']['ConvertMasterExcel'](arg1);
}

export function DistributeGroups() {
  return window['go']['main']['App']['DistributeGroups']();
}

export function GenerateGroupEvaluationPDF() {
  return window['go']['main']['App']['GenerateGroupEvaluationPDF']();
}

export function GenerateOrtsverbandCertificates() {
  return window['go']['main']['App']['GenerateOrtsverbandCertificates']();
}

export function GenerateOrtsverbandEvaluationPDF() {
  return window['go']['main']['App']['GenerateOrtsverbandEvaluationPDF']();
}

export function GeneratePDF() {
  return window['go']['main']['App']['GeneratePDF']();
}

export function GenerateParticipantCertificates() {
  return window['go']['main']['App']['GenerateParticipantCertificates']();
}

export function GetAllGroups() {
  return window['go']['main']['App']['GetAllGroups']();
}

export function GetCertLayoutJSON() {
  return window['go']['main']['App']['GetCertLayoutJSON']();
}

export function GetCertLayoutRaw() {
  return window['go']['main']['App']['GetCertLayoutRaw']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigRaw() {
  return window['go']['main']['App']['GetConfigRaw']();
}

export function GetGroupEvaluations() {
  return window['go']['main']['App']['GetGroupEvaluations']();
}

export function GetGroupPictureAsBase64(arg1) {
  return window['go']['main']['App']['GetGroupPictureAsBase64'](arg1);
}

export function GetImageAsBase64(arg1) {
  return window['go']['main']['App']['GetImageAsBase64'](arg1);
}

export function GetOrtsverbandEvaluations() {
  return window['go']['main']['App']['GetOrtsverbandEvaluations']();
}

export function HasScores() {
  return window['go']['main']['App']['HasScores']();
}

export function ListBackgroundImages() {
  return window['go']['main']['App']['ListBackgroundImages']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListGroupPictures() {
  return window['go']['main']['App']['ListGroupPictures']();
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function ResetToFreshDB() {
  return window['go']['main']['App']['ResetToFreshDB']();
}

export function RestoreDatabase(arg1) {
  return window['go']['main']['App']['RestoreDatabase'](arg1);
}

export function SaveCertLayoutJSON(arg1) {
  return window['go']['main']['App']['SaveCertLayoutJSON'](arg1);
}

export function SaveCertLayoutRaw(arg1) {
  return window['go']['main']['App']['SaveCertLayoutRaw'](arg1);
}

export function SaveConfigRaw(arg1) {
  return window['go']['main']['App']['SaveConfigRaw'](arg1);
}

export function ShowGroups() {
  return window['go']['main']['App']['ShowGroups']();
}

export function ShowStations() {
  return window['go']['main']['App']['ShowStations']();
}

export function UseExistingDB() {
  return window['go']['main']['App']['UseExistingDB']();
}
