// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignScore(arg1:number,arg2:number,arg3:number):Promise<Record<string, any>>;

export function BackupDatabase():Promise<Record<string, any>>;

export function CheckDB():Promise<Record<string, any>>;

export function GenerateGroupEvaluationPDF():Promise<Record<string, any>>;

export function GenerateOrtsverbandEvaluationPDF():Promise<Record<string, any>>;

export function GeneratePDF():Promise<Record<string, any>>;

export function GenerateParticipantCertificates():Promise<Record<string, any>>;

export function GetAllGroups():Promise<Record<string, any>>;

export function GetGroupEvaluations():Promise<Record<string, any>>;

export function GetOrtsverbandEvaluations():Promise<Record<string, any>>;

export function ListBackups():Promise<Record<string, any>>;

export function LoadFile():Promise<Record<string, any>>;

export function RestoreDatabase(arg1:string):Promise<Record<string, any>>;

export function ShowGroups():Promise<Record<string, any>>;

export function ShowStations():Promise<Record<string, any>>;
