// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStation(arg1:string):Promise<Record<string, any>>;

export function AssignScore(arg1:number,arg2:number,arg3:number):Promise<Record<string, any>>;

export function BackupDatabase():Promise<Record<string, any>>;

export function CheckDB():Promise<Record<string, any>>;

export function CheckStartup():Promise<Record<string, any>>;

export function ConvertMasterExcel(arg1:string):Promise<Record<string, any>>;

export function DeleteStation(arg1:number):Promise<Record<string, any>>;

export function DistributeGroups():Promise<Record<string, any>>;

export function GenerateGroupEvaluationPDF():Promise<Record<string, any>>;

export function GenerateOrtsverbandCertificates():Promise<Record<string, any>>;

export function GenerateOrtsverbandEvaluationPDF():Promise<Record<string, any>>;

export function GeneratePDF():Promise<Record<string, any>>;

export function GenerateParticipantCertificates():Promise<Record<string, any>>;

export function GetAllGroups():Promise<Record<string, any>>;

export function GetAllStations():Promise<Record<string, any>>;

export function GetCertLayoutJSON():Promise<Record<string, any>>;

export function GetCertLayoutRaw():Promise<Record<string, any>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetConfigRaw():Promise<Record<string, any>>;

export function GetGroupEvaluations():Promise<Record<string, any>>;

export function GetGroupPictureAsBase64(arg1:string):Promise<Record<string, any>>;

export function GetImageAsBase64(arg1:string):Promise<Record<string, any>>;

export function GetOrtsverbandEvaluations():Promise<Record<string, any>>;

export function GetOrtsverbands():Promise<Record<string, any>>;

export function GetPersonenByOrtsverband(arg1:string):Promise<Record<string, any>>;

export function HasScores():Promise<boolean>;

export function ListBackgroundImages():Promise<Record<string, any>>;

export function ListBackups():Promise<Record<string, any>>;

export function ListGroupPictures():Promise<Record<string, any>>;

export function LoadFile():Promise<Record<string, any>>;

export function ResetToFreshDB():Promise<Record<string, any>>;

export function RestoreDatabase(arg1:string):Promise<Record<string, any>>;

export function SaveCertLayoutJSON(arg1:string):Promise<Record<string, any>>;

export function SaveCertLayoutRaw(arg1:string):Promise<Record<string, any>>;

export function SaveConfigRaw(arg1:string):Promise<Record<string, any>>;

export function ShowGroups():Promise<Record<string, any>>;

export function ShowStations():Promise<Record<string, any>>;

export function UpdatePersonName(arg1:string,arg2:number,arg3:string):Promise<Record<string, any>>;

export function UpdateStationName(arg1:number,arg2:string):Promise<Record<string, any>>;

export function UseExistingDB():Promise<Record<string, any>>;
